### PR TITLE
Extract conversion function

### PR DESCRIPTION
**Pull request by dnicolson**
This pull request extracts the conversion function so it can be imported like so:

```javascript
const convertCpbitmapToPng = require('cpbitmap-to-png');
convertCpbitmapToPng(oldFile, newFile);
```

### CODE REVIEW

**Comment by hthetiot** [comment]
Nice let's do that.
Thx for contributing, I will add github action to stream line lint and tests, then if you can merge back and pass CI we can release.

**Comment by dnicolson** [comment]
Hi @hthetiot, is there something I can help with?

**Comment by hthetiot** [comment]
Sorry I was busy, let move, I will release asap.

**Comment by dnicolson** [comment]
Thanks, I rebased https://github.com/hthetiot/cpbitmap-to-png/pull/2 as well.

**Pull request merged**
